[build.branches]
PredictMD = ["develop","master",]
PredictMDExtra = ["develop","master",]
PredictMDFull = ["develop","master",]

[build.versions]
# example:
# HelloWorld = [
#     "1.0.0",
#     "2.0.0",
# ]

[clone_all_packages_in_registry]
BCBIRegistry = "26a550a3-39fe-4af4-af6d-e8814c2b6dd9"
# uncomment the next line to download ALL packages in the General registry:
# General = "23338594-aafe-5451-b93e-139f81909106"

[git.config.user]
email = "noreply@aluthge.com"
name = "Dilum Aluthge"

[package]
build = [
    "PredictMD",
    "PredictMDExtra",
    "PredictMDFull",
]
exclude = [
    "julia",
    "LibGit2",
]
move_out_of_depot = [
]
warmup = [
    "DataDeps",
    "Flux",
    "JuliaInterpreter",
]

[registry]
include = [
    "https://github.com/bcbi/BCBIRegistry",
    "https://github.com/JuliaRegistries/General",
]

[toml.manifest]
include = []

[toml.project]
include = [
    "https://raw.githubusercontent.com/bcbi/PredictMD.jl/master/Project.toml",
    "https://raw.githubusercontent.com/bcbi/PredictMD.jl/develop/Project.toml",
    "https://raw.githubusercontent.com/bcbi/PredictMDExtra.jl/master/Project.toml",
    "https://raw.githubusercontent.com/bcbi/PredictMDFull.jl/develop/Project.toml",
    "https://raw.githubusercontent.com/bcbi/PredictMDFull.jl/master/Project.toml",
    "https://raw.githubusercontent.com/bcbi/PredictMDExtra.jl/develop/Project.toml",
    "https://raw.githubusercontent.com/UnofficialJuliaMirror/MirrorUpdater.jl/master/Project.toml",
    "https://raw.githubusercontent.com/UnofficialJuliaMirrorSnapshots/Snapshots.jl/master/Project.toml",
]
