[include]
registries = [
    # To download all packages in a registry, set download_all_packages to true
    { url = "https://github.com/JuliaRegistries/General.git", download_all_packages = false },
    { url = "https://github.com/bcbi/BCBIRegistry.git", download_all_packages = false },
]
projects = [
    # Example:
    # { url = "https://raw.githubusercontent.com/MyGitHubUsername/MyPackage.jl/master/Project.toml" },
]
manifests = [
    # Example:
    # { url = "https://raw.githubusercontent.com/MyGitHubUsername/MyPackage.jl/master/Manifest.toml" },
]

[exclude]
packages = [
    "julia",
    "LibGit2",
]

[build]
packages = [
    [
        { name = "Colors"},
        { name = "JSON"},
        { name = "StatsBase"},
    ],
]

[warmup]
packages = []

[move_out_of_depot]
packages = []
