[include]
registries = [
    # To download all packages in the General, set download_all_packages to true
    { url = "https://github.com/JuliaRegistries/General", download_all_packages = false },
]
projects = [
    { url = "https://raw.githubusercontent.com/bcbi/PredictMD.jl/master/Project.toml" },
    { url = "https://raw.githubusercontent.com/bcbi/PredictMDExtra.jl/master/Project.toml" },
    { url = "https://raw.githubusercontent.com/bcbi/PredictMDFull.jl/master/Project.toml" },
]
manifests = []

[exclude]
packages = [
    "julia",
    "LibGit2",
]

[build]
packages = [
    [
        { name = "PredictMDAPI"},
    ],
    [
        { name = "PredictMDAPI", branch = "master"},
    ],
    [
        { name = "PredictMD"},
        { name = "PredictMDExtra"},
        { name = "PredictMDFull"},
    ],
    [
        { name = "PredictMD", branch = "master"},
        { name = "PredictMDExtra", branch = "master"},
        { name = "PredictMDFull", branch = "master"},
    ],
    # Examples:
    # [
    #     { name = "Foo"},
    # ],
    # [
    #     { name = "Foo"},
    #     { name = "Bar"},
    # ],
    # [
    #     { name = "Foo", version = "1.0.0"},
    # ],
    # [
    #     { name = "Bar", version = "2.0.0"},
    # ],
    # [
    #     { name = "Foo", version = "1.0.0"},
    #     { name = "Bar", version = "3.0.0"},
    # ],
    # [
    #     { name = "Foo", version = "2.0.0"},
    #     { name = "Bar", version = "4.0.0"},
    # ],
    # [
    #     { name = "Foo", branch = "master"},
    # ],
    # [
    #     { name = "Bar", branch = "master"},
    # ],
    # [
    #     { name = "Foo", branch = "master"},
    #     { name = "Bar", branch = "master"},
    # ],
]

[warmup]
packages = [
    "DataDeps",
    "Flux",
    "JuliaInterpreter",
]

[move_out_of_depot]
packages = []
